Preprocess data

In [1]:
import pandas as pd
from tqdm import tqdm
import csv

In [2]:
brandbankExtract = r'Data/Bulk Extract Full 2024.csv'

In [3]:
df = pd.read_csv(brandbankExtract)
df

C:\Users\Jack\AppData\Local\Temp\ipykernel_31884\2502181652.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(brandbankExtract)

,name,gtin,isDelete,date,pl1,pl2,pl3,description,allergyAdvice,recycling,recycling_other,brands,marketing,ingredients,features,storage,preserves
0,624880.xml,0,0,2007-10-19,Unallocated,Unallocated,Unallocated,Sainsbury's Halloween Foil Garland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,504658.xml,24,0,2005-04-29,Unallocated,Unallocated,Unallocated,Sainsbury's Aubergine,NaN,NaN,NaN,Sainsbury's,NaN,NaN,NaN,NaN,NaN
2,9602005.xml,62,1,2021-08-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,905606.xml,123,0,2010-08-16,Dairy & Bread,Morning Broken,Other,Waitrose Stonebaked Harvester Petit Pain,NaN,NaN,NaN,Waitrose,NaN,NaN,NaN,NaN,NaN
4,905597.xml,185,0,2010-08-16,Dairy & Bread,White Bread & Rolls,Other,Waitrose Fig & Raisin Loaf 400g,NaN,NaN,NaN,Waitrose,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815370,3672931.xml,9999093911090,1,2016-11-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815371,6529693.xml,9999906483929,0,2018-11-21,Meat & Fish,Reformed Meats,Other Reformed Meats,Morrisons The Best Smoked Wiltshire Cured Gamm...,NaN,NaN,NaN,Morrisons,NaN,"Pork (91%), Water, Salt, Demerara Sugar, Prese...",British pork,"Suitable for Home Freezing, Cannot be Microwav...",NaN
815372,4607178.xml,9999999999994,0,2017-07-20,Meat & Fish,Lamb,Other Lamb,Glenmór Lamb Carvery Shoulders,NaN,NaN,NaN,Glenmór,NaN,NaN,Irish country meats,NaN,NaN
815373,6771345.xml,9999999999994,0,2019-03-06,Meat & Fish,Reformed Meats,Burgers,Hogan's Farm 12 Buffalo Turkey Burgers and 12 ...,"Sulphur Dioxide/Sulphites, Contains",NaN,NaN,Hogan's Farm,NaN,"Turkey (75%), Buffalo Glaze (Acidity Regulator...","High in protein, Low in fat, Fresh class A tur...",NaN,NaN
815374,6921507.xml,9999999999994,0,2020-01-09,Meat & Fish,Chicken & Turkey,Other Turkey,Hogan's 5 Star Half Turkey Breast,"Wheat, May Contain",NaN,NaN,Hogan's,NaN,"Turkey Breast Meat, Salt, Stabilisers (Di, Tri...",NaN,Keep Refrigerated,NaN

In [4]:
df=df.fillna('')
#df = df[df['isDelete'] != 1]
df['text'] = df[[
    'description',
    'allergyAdvice',
    'recycling',
    'recycling_other',
    'brands',
    'marketing',
    'ingredients',
    'features',
    'storage',
    'preserves']].agg(' '.join, axis=1)

df.loc[df['isDelete'] == 1, 'text'] = ''


df['text'] = df['text'].str.lower()

#df['text'] = df['text'].str.replace('\n', '', regex=True)

df

,name,gtin,isDelete,date,pl1,pl2,pl3,description,allergyAdvice,recycling,recycling_other,brands,marketing,ingredients,features,storage,preserves,text
0,624880.xml,0,0,2007-10-19,Unallocated,Unallocated,Unallocated,Sainsbury's Halloween Foil Garland,,,,,,,,,,sainsbury's halloween foil garland
1,504658.xml,24,0,2005-04-29,Unallocated,Unallocated,Unallocated,Sainsbury's Aubergine,,,,Sainsbury's,,,,,,sainsbury's aubergine sainsbury's
2,9602005.xml,62,1,2021-08-13,,,,,,,,,,,,,,
3,905606.xml,123,0,2010-08-16,Dairy & Bread,Morning Broken,Other,Waitrose Stonebaked Harvester Petit Pain,,,,Waitrose,,,,,,waitrose stonebaked harvester petit pain wa...
4,905597.xml,185,0,2010-08-16,Dairy & Bread,White Bread & Rolls,Other,Waitrose Fig & Raisin Loaf 400g,,,,Waitrose,,,,,,waitrose fig & raisin loaf 400g waitrose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815370,3672931.xml,9999093911090,1,2016-11-08,,,,,,,,,,,,,,
815371,6529693.xml,9999906483929,0,2018-11-21,Meat & Fish,Reformed Meats,Other Reformed Meats,Morrisons The Best Smoked Wiltshire Cured Gamm...,,,,Morrisons,,"Pork (91%), Water, Salt, Demerara Sugar, Prese...",British pork,"Suitable for Home Freezing, Cannot be Microwav...",,morrisons the best smoked wiltshire cured gamm...
815372,4607178.xml,9999999999994,0,2017-07-20,Meat & Fish,Lamb,Other Lamb,Glenmór Lamb Carvery Shoulders,,,,Glenmór,,,Irish country meats,,,glenmór lamb carvery shoulders glenmór ir...
815373,6771345.xml,9999999999994,0,2019-03-06,Meat & Fish,Reformed Meats,Burgers,Hogan's Farm 12 Buffalo Turkey Burgers and 12 ...,"Sulphur Dioxide/Sulphites, Contains",,,Hogan's Farm,,"Turkey (75%), Buffalo Glaze (Acidity Regulator...","High in protein, Low in fat, Fresh class A tur...",,,hogan's farm 12 buffalo turkey burgers and 12 ...
815374,6921507.xml,9999999999994,0,2020-01-09,Meat & Fish,Chicken & Turkey,Other Turkey,Hogan's 5 Star Half Turkey Breast,"Wheat, May Contain",,,Hogan's,,"Turkey Breast Meat, Salt, Stabilisers (Di, Tri...",,Keep Refrigerated,,"hogan's 5 star half turkey breast wheat, may c..."

In [5]:
df['date'] = pd.to_datetime(df['date'])

df = df[df['date'].dt.year == 2023]

In [7]:

df0 = df[[
    'description',
    'allergyAdvice',
    'recycling',
    'recycling_other',
    'brands',
    'marketing',
    'ingredients',
    'features',
    'storage',
    'preserves',]]
df0['WordCount'] = df['text'].str.split().apply(len)
# Define a function to count words in a cell
def count_words(cell):
    if pd.isnull(cell):
        return 0
    return len(str(cell).split())

# Apply the function to each cell and calculate the average word count per column
average_word_count = df0.applymap(count_words).mean()

print("Average Word Count Per Column:")
print(average_word_count)

average_words_per_row = df0['WordCount'].mean()
average_words_per_row

C:\Users\Jack\AppData\Local\Temp\ipykernel_31884\2320169400.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df0['WordCount'] = df['text'].str.split().apply(len)
C:\Users\Jack\AppData\Local\Temp\ipykernel_31884\2320169400.py:20: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  average_word_count = df0.applymap(count_words).mean()

Average Word Count Per Column:
description         7.423991
allergyAdvice       3.458558
recycling           1.699727
recycling_other     2.674135
brands              1.194813
marketing          54.802959
ingredients        27.878403
features           23.903878
storage             0.841246
preserves           0.622930
WordCount           1.000000
dtype: float64

124.50063953612313

In [6]:
# Calculate the number of words in each row of the 'text' column
df['WordCount'] = df['text'].str.split().apply(len)

# Calculate the average number of words per row
average_words_per_row = df['WordCount'].mean()
average_words_per_row

C:\Users\Jack\AppData\Local\Temp\ipykernel_31884\3187587090.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WordCount'] = df['text'].str.split().apply(len)

124.50063953612313

In [25]:
df

,name,gtin,isDelete,date,pl1,pl2,pl3,description,allergyAdvice,recycling,recycling_other,brands,marketing,ingredients,features,storage,preserves,text
23,12033288.xml,6606,0,2023-06-12,Household & Garden,Plants,Cut Flowers,Asda Daffodils,,,,Asda,,,Carefully selected,,,asda daffodils asda carefully selected
28,12192656.xml,765,0,2023-08-04,Fruit & Vegetables,Exotic Fruit,Other Exotic Fruit,Waitrose & Partners Dragon Fruit,,,,Waitrose,,,,,,waitrose & partners dragon fruit waitrose
375,12334437.xml,8792,0,2023-09-29,Fruit & Vegetables,Core Vegetables,Squashes,JS Mixed Squash Loose,,,,Unbranded,,,,,,js mixed squash loose unbranded
377,12389169.xml,8945,0,2023-11-01,Fruit & Vegetables,Exotic Fruit,Pineapples,Sainsbury's Crownless Pineapple,,,,Sainsbury's,,,,,,sainsbury's crownless pineapple sainsbury's...
407,11082692.xml,12119,0,2023-01-19,Grocery,Jams & Spreads,Jams,Sainsbury's Blackcurrant Jam 454g,,"Lid, Recycle",Lid On - Rinse - Jar - Recycle,Sainsbury's,,"Sugar, Blackcurrants, Water, Acidity Regulator...",Suitable for vegans,,,"sainsbury's blackcurrant jam 454g lid, recycl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815306,11125808.xml,9781915306289,0,2023-01-13,Household & Garden,News & Magazines,Books,Doomsday Mother - John Glatt,,,,,The Doomsday Mother is the astonishing and twi...,,,,,doomsday mother - john glatt the doomsday ...
815307,11977090.xml,9781915306326,0,2023-04-26,Household & Garden,News & Magazines,Books,Abandoned - Monica Allan,,,,,"""It was like going through a door which had be...",,,,,"abandoned - monica allan ""it was like goin..."
815308,12096367.xml,9781915306401,0,2023-06-13,Household & Garden,News & Magazines,Books,Groomed By A Gang - Christina O'Connor,,,,,"""He had raped me, had me beaten up, drained me...",,,,,"groomed by a gang - christina o'connor ""he..."
815309,12447950.xml,9781915306555,0,2023-10-02,Household & Garden,News & Magazines,Books,Sparkle's Story - Louise Allen,,,,,Louise gets a frantic call to take in a damage...,,,,,sparkle's story - louise allen louise gets...
815345,12143965.xml,9782764356821,0,2023-07-04,Household & Garden,News & Magazines,Books,Disney Mickey 100 My Busy Books Limited Editio...,,,,,,,,,,disney mickey 100 my busy books limited editio...

RAKE_NLTK

In [11]:
from rake_nltk import Rake
import nltk
r = Rake()

In [12]:
def get_num_words(row):
    return len(str(row['Phrase']).split())

def get_perc_phrase(row,total):
    return (float(row['Score'])/total*100)

In [13]:
def get_Rake_phrases(df):
    r = Rake()
    r.extract_keywords_from_sentences(df['text'])
    phrases=r.get_ranked_phrases_with_scores()
    df = pd.DataFrame(phrases, columns = ['Rank', 'Phrase'])
    df['Phrase'] = df['Phrase'].str.strip()
    phrase_counts = df['Phrase'].value_counts()
    phrase_counts = phrase_counts.reset_index()
    phrase_counts.columns=['Phrase','Score']
    phrase_counts['Length'] = phrase_counts.apply (lambda row: get_num_words(row), axis=1)
    phrase_counts=phrase_counts.loc[phrase_counts['Length'] <=6]
    total = float(phrase_counts['Score'].sum())
    phrase_counts['Perc'] = phrase_counts.apply (lambda row: get_perc_phrase(row,total), axis=1)
    return phrase_counts

In [80]:
df_raked = get_Rake_phrases(df)
#phrase_counts.to_csv(r'C:\Users\Clamfighter\Documents\GitHub\NLP\Impact Score Key Phrase\Extracted Phrases\Rake NLTK\Brandbank Latest Phrase Extraction.csv',index = False)

In [81]:
df_raked

                            Phrase  Score  Length      Perc
0                      may contain  41378       2  0.900442
1                         contains  38374       1  0.835071
2                          recycle  36823       1  0.801319
3                         suitable  28674       1  0.623986
4                             salt  25486       1  0.554611
...                            ...    ...     ...       ...
481483               microwave 8 1      1       3  0.000022
481484     sweetened codensed milk      1       3  0.000022
481485  jurassic shark .' la times      1       5  0.000022
481486       morrisons zingy mango      1       3  0.000022
481487          eight harry potter      1       3  0.000022

[428896 rows x 4 columns]

In [82]:
pattern = r'[^a-zA-Z ]'

df_raked = df_raked[~df_raked['Phrase'].str.contains(pattern, regex=True, na=False)]

In [83]:
df_raked

                         Phrase  Score  Length      Perc
0                   may contain  41378       2  0.900442
1                      contains  38374       1  0.835071
2                       recycle  36823       1  0.801319
3                      suitable  28674       1  0.623986
4                          salt  25486       1  0.554611
...                         ...    ...     ...       ...
481480   classic fine structure      1       3  0.000022
481481           every shaver p      1       3  0.000022
481484  sweetened codensed milk      1       3  0.000022
481486    morrisons zingy mango      1       3  0.000022
481487       eight harry potter      1       3  0.000022

[285670 rows x 4 columns]

In [46]:
phrase_count=[]

#df_phraseCount = df_raked.loc[df_raked['Score'] != 1] #filters Score of 1 out. will be added back in later
phrases = df_raked['Phrase']
text = df['text']
for phrase in tqdm(phrases): #find number of phrases for all strings
    phrase_count.append(sum(phrase in s for s in text))
phrase_count

  0%|          | 0/285670 [00:00<?, ?it/s]

100%|██████████| 285670/285670 [4:34:04<00:00, 17.37it/s]

[15439,
 40374,
 38577,
 31143,
 26821,
 29428,
 30761,
 21609,
 25865,
 18211,
 16383,
 11176,
 16115,
 13476,
 22264,
 8958,
 10616,
 14824,
 8901,
 9459,
 10593,
 85753,
 8490,
 16858,
 9535,
 6831,
 9763,
 24059,
 10005,
 7379,
 7138,
 13436,
 20358,
 12775,
 7021,
 7574,
 7016,
 7256,
 6697,
 7458,
 4066,
 7897,
 6369,
 5993,
 5063,
 14459,
 8254,
 3516,
 10250,
 10645,
 11510,
 5229,
 8023,
 6614,
 6831,
 9093,
 6443,
 5497,
 14509,
 4519,
 9569,
 4589,
 5137,
 5084,
 11035,
 8886,
 13909,
 9166,
 5781,
 10760,
 4763,
 8892,
 10623,
 4832,
 3924,
 4817,
 4154,
 5389,
 4087,
 3862,
 20918,
 13602,
 10252,
 11270,
 3836,
 5049,
 5013,
 10655,
 5055,
 4856,
 3536,
 4052,
 6708,
 2893,
 5664,
 3538,
 81897,
 24289,
 9455,
 3557,
 10110,
 5465,
 6882,
 4149,
 5688,
 6559,
 7610,
 2785,
 9078,
 3370,
 7770,
 32742,
 5300,
 6345,
 7191,
 26621,
 8712,
 33030,
 16746,
 1646,
 88703,
 9798,
 3059,
 11617,
 2398,
 6019,
 26857,
 2798,
 9604,
 3026,
 3520,
 14061,
 9113,
 5228,
 6364,
 3926,
 4455,
 3296,
 3606,
 40499,
 28104,
 11124,
 5418,
 3097,
 7154,
 5124,
 12236,
 3948,
 3380,
 10338,
 9885,
 6036,
 7622,
 9828,
 3777,
 5983,
 3602,
 14848,
 11202,
 3754,
 2721,
 3270,
 2706,
 12419,
 2520,
 4381,
 1363,
 2530,
 85291,
 81514,
 2433,
 4520,
 4609,
 877,
 7944,
 5378,
 3553,
 2841,
 11766,
 23991,
 6352,
 1654,
 13660,
 3036,
 3579,
 3329,
 19265,
 3195,
 14613,
 3055,
 3346,
 3396,
 9819,
 8611,
 4489,
 4243,
 3310,
 6725,
 7597,
 5316,
 3100,
 3445,
 2277,
 3218,
 2778,
 2989,
 9039,
 2199,
 1934,
 12049,
 20115,
 2485,
 11280,
 8528,
 1812,
 6784,
 6963,
 2028,
 12722,
 8918,
 5076,
 4396,
 7615,
 2160,
 3124,
 2062,
 20271,
 5203,
 5940,
 2727,
 1791,
 10779,
 1871,
 1843,
 8940,
 2057,
 3738,
 4726,
 3786,
 13497,
 8319,
 2046,
 5822,
 21060,
 62761,
 2265,
 1622,
 1560,
 992,
 4243,
 9603,
 1777,
 3159,
 3268,
 8442,
 2682,
 9075,
 4495,
 2389,
 2605,
 2737,
 5800,
 2670,
 6826,
 1298,
 7590,
 1684,
 8004,
 3690,
 4219,
 2353,
 1874,
 3485,
 2528,
 31643,
 3691,
 2428,
 2096,
 2029,
 4745,
 2137,
 2936,
 4645,
 24081,
 3441,
 2683,
 1613,
 2374,
 2267,
 10320,
 1783,
 7897,
 4589,
 8580,
 4686,
 1701,
 2820,
 2778,
 3021,
 1401,
 2502,
 5489,
 2030,
 1695,
 1528,
 4298,
 2090,
 5818,
 10370,
 1553,
 2060,
 2270,
 1503,
 4190,
 4938,
 1372,
 3404,
 3293,
 1821,
 4047,
 3367,
 2166,
 2490,
 4683,
 2305,
 3138,
 970,
 1830,
 1373,
 1513,
 25773,
 3079,
 3769,
 2847,
 4306,
 1275,
 1721,
 2436,
 2828,
 1933,
 2057,
 2913,
 2179,
 4047,
 1926,
 5392,
 6575,
 1375,
 2545,
 1418,
 3927,
 3186,
 8181,
 8474,
 1743,
 1211,
 1898,
 2378,
 4960,
 1217,
 3526,
 3553,
 5065,
 1443,
 1227,
 2112,
 11080,
 1448,
 3129,
 1814,
 1822,
 4911,
 2246,
 8360,
 8068,
 1765,
 1886,
 1254,
 1739,
 1297,
 1445,
 2435,
 1891,
 1109,
 1054,
 1858,
 3779,
 1167,
 1733,
 3942,
 1463,
 4798,
 3258,
 6405,
 84022,
 1763,
 3116,
 2153,
 1193,
 2215,
 2910,
 8006,
 757,
 1834,
 1510,
 1177,
 1917,
 1466,
 1255,
 1540,
 1188,
 1233,
 1485,
 1753,
 9728,
 3519,
 3056,
 91453,
 1459,
 1148,
 1816,
 2755,
 8619,
 1909,
 2161,
 2428,
 4379,
 1788,
 1501,
 1003,
 2563,
 5288,
 1123,
 1525,
 1906,
 1158,
 1086,
 1622,
 1151,
 3561,
 2792,
 2101,
 3783,
 2988,
 1571,
 1084,
 2096,
 1435,
 1144,
 2307,
 4876,
 6571,
 2927,
 1150,
 1623,
 1149,
 1932,
 1875,
 1109,
 1088,
 2147,
 1396,
 5768,
 1127,
 12174,
 10012,
 2145,
 918,
 7558,
 2439,
 1533,
 2397,
 1520,
 1216,
 955,
 1012,
 2572,
 805,
 967,
 1306,
 19968,
 2649,
 1954,
 2659,
 14161,
 4553,
 6697,
 1373,
 1614,
 1584,
 655,
 1966,
 1132,
 1033,
 1030,
 2148,
 1821,
 748,
 1023,
 29910,
 2201,
 6553,
 3773,
 1302,
 1406,
 910,
 4254,
 5824,
 365,
 939,
 507,
 6453,
 6255,
 1329,
 2933,
 1411,
 1401,
 996,
 2039,
 1773,
 1551,
 3256,
 5358,
 606,
 12048,
 985,
 4399,
 900,
 10148,
 250,
 1249,
 89362,
 2303,
 6103,
 1077,
 1556,
 1027,
 4269,
 5956,
 1273,
 1386,
 4810,
 6690,
 6842,
 1127,
 1333,
 1930,
 2116,
 961,
 1038,
 1979,
 1265,
 2803,
 630,
 1075,
 1899,
 4751,
 2965,
 1189,
 13952,
 3485,
 942,
 7545,
 1125,
 5147,
 2892,
 1538,
 11091,
 1552,
 3502,
 3676,
 3010,
 898,
 3980,
 2433,
 143,
 825,
 1403,
 3623,
 2064,
 1099,
 1486,
 937,
 3513,
 930,
 1418,
 881,
 1585,
 3579,
 1474,
 2388,
 1897,
 41399,
 1075,
 687,
 12119,
 1930,
 890,
 876,
 1105,
 2267,
 1109,
 868,
 3736,
 4918,
 7278,
 1262,
 3433,
 2574,
 301,
 915,
 5220,
 17934,
 688,
 1677,
 5473,
 1588,
 821,
 1169,
 2729,
 5843,
 2800,
 1914,
 1295,
 866,
 845,
 3144,
 2229,
 1105,
 4524,
 1104,
 4354,
 7258,
 1025,
 4496,
 3190,
 717,
 660,
 6360,
 12395,
 956,
 2488,
 933,
 6938,
 1420,
 823,
 2094,
 4076,
 2652,
 722,
 2044,
 2377,
 963,
 3048,
 89726,
 2701,
 9010,
 725,
 4599,
 1189,
 779,
 3503,
 819,
 1321,
 141,
 1195,
 1027,
 1439,
 1777,
 1895,
 3297,
 1091,
 748,
 744,
 1413,
 649,
 988,
 1264,
 962,
 3873,
 796,
 1131,
 676,
 881,
 7102,
 1504,
 744,
 1650,
 1077,
 676,
 126,
 1235,
 3422,
 1107,
 724,
 1642,
 1470,
 16020,
 724,
 29356,
 5724,
 902,
 1381,
 2569,
 1046,
 4650,
 1861,
 728,
 2734,
 825,
 875,
 1615,
 1570,
 1444,
 1264,
 789,
 4323,
 2002,
 755,
 860,
 33526,
 799,
 698,
 4767,
 2319,
 2809,
 13571,
 3355,
 2788,
 613,
 839,
 1202,
 783,
 1955,
 798,
 1332,
 1023,
 6053,
 4304,
 1378,
 10345,
 676,
 1076,
 389,
 715,
 2813,
 677,
 726,
 2713,
 673,
 2229,
 1455,
 848,
 476,
 652,
 5569,
 3081,
 12008,
 2233,
 944,
 715,
 621,
 2092,
 1117,
 621,
 1727,
 1527,
 668,
 126,
 7388,
 1676,
 1208,
 5042,
 1241,
 936,
 1713,
 1954,
 872,
 1158,
 1578,
 11248,
 5060,
 4750,
 582,
 1741,
 6648,
 25869,
 1023,
 1246,
 4306,
 535,
 1443,
 754,
 1117,
 1225,
 638,
 2527,
 1595,
 1134,
 1499,
 872,
 2056,
 7429,
 1125,
 702,
 808,
 7970,
 1046,
 2488,
 3591,
 2824,
 10496,
 1224,
 475,
 978,
 2467,
 1469,
 600,
 1389,
 1114,
 1621,
 621,
 619,
 1327,
 958,
 1298,
 619,
 329,
 906,
 3106,
 6778,
 1066,
 519,
 585,
 902,
 1588,
 1345,
 1157,
 794,
 3794,
 1686,
 909,
 623,
 7382,
 586,
 295,
 605,
 5285,
 1113,
 358,
 1425,
 1832,
 683,
 9209,
 18346,
 786,
 1123,
 2002,
 633,
 1519,
 822,
 2745,
 335,
 587,
 1115,
 614,
 1741,
 1282,
 1915,
 987,
 5045,
 581,
 513,
 1573,
 975,
 506,
 749,
 430,
 1142,
 1997,
 794,
 1497,
 2869,
 1169,
 388,
 1279,
 1557,
 701,
 403,
 943,
 1655,
 3567,
 1106,
 1150,
 1285,
 3935,
 355,
 651,
 820,
 388,
 1810,
 1279,
 287,
 517,
 3169,
 643,
 2834,
 1518,
 561,
 364,
 1512,
 520,
 940,
 3035,
 390,
 629,
 683,
 2818,
 345,
 14172,
 551,
 800,
 552,
 1041,
 1246,
 2519,
 590,
 1363,
 1479,
 1703,
 1047,
 1742,
 2425,
 614,
 10488,
 393,
 2876,
 644,
 588,
 519,
 1176,
 617,
 1400,
 602,
 483,
 552,
 562,
 881,
 1061,
 544,
 809,
 445,
 541,
 434,
 1017,
 914,
 575,
 1216,
 758,
 2584,
 1833,
 3030,
 510,
 261,
 2122,
 2008,
 800,
 407,
 1676,
 1502,
 8247,
 4054,
 4355,
 571,
 668,
 2295,
 750,
 957,
 1066,
 1360,
 1545,
 499,
 471,
 827,
 654,
 748,
 2904,
 861,
 1096,
 4499,
 468,
 423,
 674,
 3334,
 494,
 1840,
 518,
 539,
 825,
 539,
 ...]

In [84]:
df_phraseCount = df_raked
df_phraseCount['Count'] = phrase_count
df_out = df_phraseCount

ValueError: Length of values (264) does not match length of index (285670)

In [63]:
df_out

,Phrase,Score,Length,Perc,Count,Percentage Count
0,may contain,41378,2,0.900442,15439,16.456330
1,contains,38374,1,0.835071,40374,43.034386
2,recycle,36823,1,0.801319,38577,41.118975
3,suitable,28674,1,0.623986,31143,33.195122
4,salt,25486,1,0.554611,26821,28.588331
...,...,...,...,...,...,...
481480,classic fine structure,1,3,0.000022,1,0.001066
481481,every shaver p,1,3,0.000022,0,0.000000
481484,sweetened codensed milk,1,3,0.000022,1,0.001066
481486,morrisons zingy mango,1,3,0.000022,1,0.001066
481487,eight harry potter,1,3,0.000022,1,0.001066

In [62]:
df_out['Percentage Count'] = (df_out['Count'] / 93818) * 100

C:\Users\Jack\AppData\Local\Temp\ipykernel_6796\2412878027.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_out['Percentage Count'] = (df_out['Count'] / 93818) * 100

In [64]:
df_out.to_csv(r'Data/Phrases 2023.csv',index = False)

In [71]:
df_phrases = pd.read_csv('Data\Filtered Phrases.csv')
df_phrases['Score'] = None
df_phrases['Length'] = df_phrases['Phrase'].str.split().str.len()
df_phrases['Perc'] = None
phrase_count = []
phrases = df_phrases['Phrase']
text = df['text']
for phrase in tqdm(phrases): #find number of phrases for all strings
    phrase_count.append(sum(phrase in s for s in text))
phrase_count

<>:1: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\F'
C:\Users\Jack\AppData\Local\Temp\ipykernel_6796\2263859382.py:1: SyntaxWarning: invalid escape sequence '\F'
  df_phrases = pd.read_csv('Data\Filtered Phrases.csv')
100%|██████████| 264/264 [00:10<00:00, 24.04it/s]

[0,
 0,
 6345,
 2057,
 1291,
 14,
 1279,
 0,
 355,
 34,
 2,
 0,
 0,
 0,
 5586,
 430,
 0,
 2,
 189,
 0,
 4076,
 226,
 1,
 3138,
 0,
 2028,
 1655,
 23,
 16,
 48,
 0,
 41,
 0,
 504,
 0,
 16,
 0,
 206,
 0,
 1,
 956,
 0,
 0,
 1713,
 793,
 474,
 688,
 2798,
 686,
 409,
 1,
 25,
 0,
 5,
 94,
 0,
 8703,
 0,
 23,
 0,
 2057,
 1123,
 0,
 2,
 0,
 0,
 0,
 0,
 22,
 591,
 135,
 10,
 37,
 1821,
 3579,
 465,
 239,
 0,
 478,
 281,
 166,
 1629,
 0,
 1519,
 4599,
 0,
 0,
 11,
 0,
 0,
 0,
 0,
 0,
 1163,
 8247,
 243,
 193,
 264,
 666,
 369,
 2563,
 2112,
 239,
 369,
 7379,
 285,
 0,
 0,
 940,
 693,
 0,
 1474,
 1448,
 237,
 1,
 0,
 18,
 5076,
 1093,
 8888,
 2,
 0,
 23,
 2531,
 3,
 0,
 0,
 0,
 20271,
 2,
 0,
 3,
 42,
 8,
 1354,
 4912,
 21060,
 720,
 3,
 6784,
 3329,
 1109,
 1843,
 909,
 863,
 174,
 121,
 84,
 44,
 0,
 1,
 2219,
 1812,
 1776,
 662,
 681,
 0,
 0,
 2569,
 48,
 45,
 452,
 473,
 2435,
 8,
 2147,
 14459,
 282,
 651,
 313,
 0,
 1874,
 2420,
 617,
 2729,
 0,
 0,
 1504,
 1520,
 916,
 38577,
 11510,
 1023,
 2199,
 296,
 2727,
 1,
 13,
 0,
 2,
 0,
 0,
 6,
 0,
 0,
 10,
 0,
 1162,
 286,
 393,
 17,
 0,
 141,
 249,
 0,
 0,
 0,
 394,
 12048,
 1,
 823,
 3433,
 0,
 0,
 0,
 2622,
 185,
 5,
 0,
 2,
 2,
 54,
 110,
 0,
 0,
 3591,
 2425,
 5389,
 76,
 7,
 69,
 22,
 13660,
 1216,
 9535,
 355,
 677,
 473,
 757,
 17900,
 1443,
 16115,
 605,
 1613,
 1033,
 954,
 458,
 0,
 0,
 0,
 0,
 252,
 2847,
 55,
 16,
 5,
 0,
 642,
 3129,
 0,
 0,
 60,
 0,
 0]

In [73]:
df_phraseCount = df_phrases
df_phraseCount['Count'] = phrase_count
df_out = df_phrases
df_out['Percentage Count'] = (df_out['Count'] / 93818) * 100

In [74]:
df_out

,Phrase,Score,Length,Perc,Count,Percentage Count
0,﻿active ingredient,None,2,None,0,0.000000
1,advocate for environmental protection,None,4,None,0,0.000000
2,antioxidant,None,1,None,6345,6.763095
3,baby,None,1,None,2057,2.192543
4,beauty,None,1,None,1291,1.376069
...,...,...,...,...,...,...
259,worker safety,None,2,None,0,0.000000
260,zero discharge,None,2,None,0,0.000000
261,zero waste,None,2,None,60,0.063954
262,zero waste design,None,3,None,0,0.000000
263,zero waste movement,None,3,None,0,0.000000

In [65]:
def calculate_frequency_change(current_year_df, previous_year_df, phrase_column='Phrase', frequency_column='Percentage Count'):
    """
    Calculates the change in frequency for phrases between two DataFrames, considering both
    increases and decreases in frequency, as well as phrases exclusive to each DataFrame.
    Assigns 100 to new phrases in the current year and -100 to phrases only found in the previous year.
    Keeps the phrase from the previous year.

    :param current_year_df: DataFrame for the current year.
    :param previous_year_df: DataFrame for the previous year.
    :param phrase_column: The name of the column containing the phrases.
    :param frequency_column: The name of the column containing the frequency percentages.
    :return: DataFrame with phrases and their change in frequency, including all other columns.
    """

    # Convert the phrase column to lowercase for consistent comparison
    current_year_df[phrase_column] = current_year_df[phrase_column].str.lower()
    previous_year_df[phrase_column] = previous_year_df[phrase_column].str.lower()

    # Merge the two DataFrames on the phrase column
    merged_df = pd.merge(current_year_df, previous_year_df, on=phrase_column, how='outer', suffixes=('_current', '_previous'))

    # Fill NaN values for the frequency columns
    merged_df[f"{frequency_column}_current"].fillna(0, inplace=True)
    merged_df[f"{frequency_column}_previous"].fillna(0, inplace=True)

    # Calculate the change in frequency
    # If the phrase is only in the current year, the change should be 100.
    # If the phrase is only in the previous year, the change should be -100.
    # Otherwise, it's the difference between the current and previous frequency.
    merged_df['frequency_change'] = merged_df.apply(
        lambda row: 100 if pd.isnull(row[f"{frequency_column}_previous"]) else
                    (-100 if pd.isnull(row[f"{frequency_column}_current"]) else
                     row[f"{frequency_column}_current"] - row[f"{frequency_column}_previous"]),
        axis=1
    )

    # Sort by the absolute change in frequency to see the most significant changes
    merged_df.sort_values(by='frequency_change', ascending=False, inplace=True)

    return merged_df

In [86]:
df_2022 = pd.read_csv(r'Data/Phrases 2022.csv')

In [85]:
df_2023 = pd.read_csv(r'Data/Phrases 2023.csv')

In [87]:
frequency_df = calculate_frequency_change(current_year_df=df_2023, previous_year_df=df_2022)

In [88]:
frequency_df

,Phrase,Score_current,Length_current,Perc_current,Count_current,Percentage Count_current,Score_previous,Length_previous,Perc_previous,Count_previous,Percentage Count_previous,frequency_change
18287,ed,19.0,1.0,0.000413,78963.0,84.166151,NaN,NaN,NaN,NaN,0.000000,84.166151
197782,se,1.0,1.0,0.000022,73155.0,77.975442,NaN,NaN,NaN,NaN,0.000000,77.975442
160496,ic,1.0,1.0,0.000022,72593.0,77.376410,NaN,NaN,NaN,NaN,0.000000,77.376410
62334,ea,4.0,1.0,0.000087,72445.0,77.218657,NaN,NaN,NaN,NaN,0.000000,77.218657
172547,ti,1.0,1.0,0.000022,72122.0,76.874374,NaN,NaN,NaN,NaN,0.000000,76.874374
...,...,...,...,...,...,...,...,...,...,...,...,...
297752,pa,NaN,NaN,NaN,NaN,0.000000,2.0,1.0,0.000118,23996.0,47.822708,-47.822708
287215,wi,NaN,NaN,NaN,NaN,0.000000,6.0,1.0,0.000353,25767.0,51.352213,-51.352213
324046,ns,NaN,NaN,NaN,NaN,0.000000,1.0,1.0,0.000059,29476.0,58.744046,-58.744046
344440,ur,NaN,NaN,NaN,NaN,0.000000,1.0,1.0,0.000059,31827.0,63.429460,-63.429460
287394,te,NaN,NaN,NaN,NaN,0.000000,5.0,1.0,0.000294,36218.0,72.180481,-72.180481

In [89]:
frequency_df.to_csv(r'Data/Phrases Frequency Change 22-23.csv',index = False)